server:
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://root:root@localhost/files?authSource=admin

  servlet:
    multipart:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

file:
  upload-dir: uploads/